# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch 
import numpy as np
# Create random tensor
a = torch.tensor(np.random.rand(7,7))
print(a)

tensor([[0.6245, 0.4611, 0.0132, 0.2693, 0.2851, 0.1746, 0.8856],
        [0.2319, 0.7674, 0.9823, 0.7619, 0.2629, 0.3363, 0.5008],
        [0.9928, 0.3518, 0.0520, 0.1070, 0.0055, 0.1328, 0.7722],
        [0.7204, 0.3449, 0.1843, 0.8634, 0.2663, 0.4127, 0.5116],
        [0.7882, 0.0293, 0.3197, 0.6257, 0.2793, 0.2501, 0.4087],
        [0.4181, 0.6417, 0.0633, 0.3814, 0.2477, 0.4278, 0.4166],
        [0.5467, 0.5825, 0.3248, 0.8159, 0.0114, 0.4799, 0.4435]],
       dtype=torch.float64)


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [7]:
# Create another random tensor
b = torch.tensor(np.random.rand(1,7))

# Perform matrix multiplication 
b = torch.t(b)

c = a@b
print(c)

tensor([[1.3656],
        [2.4601],
        [0.8951],
        [1.6921],
        [1.2043],
        [1.5553],
        [1.7762]], dtype=torch.float64)


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [20]:
# Set manual seed
torch.manual_seed(0)
# Create two random tensors
a = torch.rand(7,7)
b = torch.rand(1,7)

# Matrix multiply tensors

b = torch.transpose(b, 0, 1)

c=a@b
print(c)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [15]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [34]:
# Set random seed
torch.cuda.manual_seed(1234)
torch.manual_seed(1234)
# Check for access to GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# Create two random tensors on GPU

a = torch.rand((2, 3), device=device)
b = torch.rand((2, 3), device=device)

print("First Tensor:", a)
print("Second Tensor:", b)


First Tensor: tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
Second Tensor: tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [35]:
# Perform matmul on tensor_A and tensor_B
b=torch.transpose(b,0,1)

c = torch.matmul(a,b)
print(c)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])


### 8. Find the maximum and minimum values of the output of 7.

In [36]:
# Find max
print(torch.max(c))

# Find min
print(torch.min(c))

tensor(0.5617)
tensor(0.3647)


### 9. Find the maximum and minimum index values of the output of 7.

In [38]:
# Find arg max
print(torch.argmax(c))

# Find arg min
print(torch.argmin(c))

tensor(3)
tensor(0)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [41]:
# Set seed
torch.manual_seed(7)

# Create random tensor
a = torch.rand(1,1,1,10)

# Remove single dimensions
b = torch.squeeze(a)

# Print out tensors and their shapes
print(a, a.shape)
print(b, b.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
